defaults:
  - _self_
  - scenario_runner: apollo_sim
  - scenario: borregas_ave_t1
  - engine: random

tag: run_1
output_root: results/random
debug: true
resume: true
save_record: true

hydra:
  job:
    chdir: False
  run:
    dir: disabled